trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build || echo "no build step"
    npm test || echo "no tests"
  displayName: 'Install dependencies & build'

- script: |
    npm start &
    sleep 5
    curl http://localhost:3000
  displayName: 'Run app & test endpoint'
