# Generated by Django 4.1.7 on 2023-08-06 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.TextField(max_length=50)),
                ('publish_date', models.TextField(max_length=50)),
                ('pages', models.TextField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Hidden', 'Hidden'), ('in Use', 'in Use'), ('Available', ' Available')], default='Available', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=225)),
                ('mail', models.CharField(max_length=225)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('returndate', models.DateTimeField(default=None, null=True)),
                ('book_title', models.CharField(default=None, max_length=225, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower_book', to='store.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower_username', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Borrowers',
            },
        ),
    ]
