# Generated by Django 4.1.7 on 2023-08-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='user',
            new_name='userid',
        ),
    ]
