# Generated by Django 4.1.7 on 2023-08-06 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_rename_user_borrower_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='userid',
        ),
        migrations.AddField(
            model_name='borrower',
            name='book_author',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
