# Generated by Django 4.1.7 on 2023-08-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_borrower_userid_borrower_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='date',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='returndate',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
