# Generated by Django 4.1.7 on 2023-08-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_borrower_returndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
