# Generated by Django 4.1.7 on 2023-08-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_token_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
